# Generated by Django 6.0.4 on 2026-04-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dutch_text', models.CharField(max_length=50)),
                ('translation', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('word', 'Word'), ('digraph', 'Digraph')], max_length=20)),
                ('pronunciation_audio', models.CharField(max_length=250)),
            ],
        ),
    ]
