# Generated by Django 6.0.4 on 2026-04-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main'), ('example', 'Example')], max_length=20)),
                ('order', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.vocabulary')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='words',
            field=models.ManyToManyField(through='courses.LessonVocabulary', to='courses.vocabulary'),
        ),
    ]
