# Generated by Django 6.0.4 on 2026-04-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonvocabulary_lesson_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonvocabulary',
            options={'verbose_name_plural': 'Lesson Vocabularies'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name_plural': 'Vocabularies'},
        ),
        migrations.RemoveField(
            model_name='lessonvocabulary',
            name='order',
        ),
    ]
