# Generated by Django 6.0.4 on 2026-04-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lessonvocabulary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvocabulary',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
